// <auto-generated />
namespace FleaMarket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class aspnetFleaMarket20161202021115 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aspnetFleaMarket20161202021115));
        
        string IMigrationMetadata.Id
        {
            get { return "201612271427435_aspnet-FleaMarket-20161202021115"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
